-- Add sample products to database
-- Products with real images and complete specifications

INSERT INTO products (title, description, price, image_url, category, brand, model, features, specifications, status, created_at, updated_at) VALUES
('Vaillant ecoTEC Plus', 'Yüksek verimli kondenzli kombi. Modülasyonlu yanma sistemi ile ekonomik ve çevre dostu ısıtma çözümü sunar.', 12500, '/uploads/products/vaillant-ecotec-plus.png', 'kombi', 'Vaillant', 'ecoTEC Plus', '["Kondenzli teknoloji","Yüksek verim (%108)","Modülasyonlu yanma","Kompakt tasarım","Sessiz çalışma"]', '{"Güç":"24 kW","Verim":"%108","Boyutlar":"720x440x338 mm","Ağırlık":"34 kg","Gaz Bağlantısı":"3/4\"","Su Bağlantısı":"3/4\"","Garanti":"2 yıl"}', 'active', datetime('now'), datetime('now')),

('Bosch Condens 8300iW', 'Akıllı kondenzli kombi sistemi. WiFi bağlantısı ve uzaktan kontrol özelliği ile modern yaşam için ideal.', 14800, '/uploads/products/bosch-condens-8300iw.png', 'kombi', 'Bosch', 'Condens 8300iW', '["WiFi bağlantısı","Uzaktan kontrol","Kondenzli teknoloji","Otomatik ayar","Ekonomik mod"]', '{"Güç":"28 kW","Verim":"%109","Boyutlar":"720x400x299 mm","Ağırlık":"32 kg","WiFi":"Evet","Garanti":"2 yıl"}', 'active', datetime('now'), datetime('now')),

('Baymak Elegant Plus Klima', 'Inverter teknolojili split klima. Sessiz çalışma ve yüksek enerji verimliliği ile konforlu soğutma.', 8900, '/uploads/products/baymak-elegant-plus-klima.png', 'klima', 'Baymak', 'Elegant Plus', '["Inverter teknoloji","Sessiz çalışma","Hızlı soğutma","Otomatik temizlik","Wi-Fi hazır"]', '{"Soğutma Kapasitesi":"12000 BTU/h","Enerji Sınıfı":"A++","Ses Seviyesi":"19 dB","Çalışma Sıcaklığı":"-15°C / +50°C","Garanti":"3 yıl"}', 'active', datetime('now'), datetime('now')),

('Buderus Logamax Plus GB122i', 'Yoğuşmalı kombi sistemi. Dayanıklı yapısı ve yüksek performansı ile uzun yıllar güvenilir hizmet sunar.', 11200, '/uploads/products/buderus-logano-plus.png', 'kombi', 'Buderus', 'GB122i', '["Yoğuşmalı teknoloji","Dayanıklı yapı","Otomatik ayar","Kompakt boyut","Kolay bakım"]', '{"Güç":"25 kW","Verim":"%107","Boyutlar":"740x440x360 mm","Ağırlık":"39 kg","Garanti":"2 yıl"}', 'active', datetime('now'), datetime('now')),

('Daikin Altherma Isı Pompası', 'Çevre dostu ısı pompası sistemi. Hem ısıtma hem soğutma özelliği ile tüm mevsimler için ideal çözüm.', 24500, '/uploads/products/daikin-altherma.jpg', 'ısı-pompası', 'Daikin', 'Altherma', '["Çevre dostu","Isıtma/Soğutma","Yüksek COP","Sessiz işletim","Akıllı kontrol"]', '{"Güç":"16 kW","COP":"4.5","Çalışma Sıcaklığı":"-25°C / +35°C","Ses Seviyesi":"58 dB","Garanti":"5 yıl"}', 'active', datetime('now'), datetime('now')),

('ECA Confeo Kombi', 'Türk malı kondenzli kombi. Yerel üretim avantajı ve uygun fiyatı ile ekonomik ısıtma çözümü.', 9800, '/uploads/products/eca-confeo-kombi.png', 'kombi', 'ECA', 'Confeo', '["Türk malı","Kondenzli sistem","Ekonomik fiyat","Kolay kurulum","Yerel servis"]', '{"Güç":"24 kW","Verim":"%105","Boyutlar":"730x400x315 mm","Ağırlık":"28 kg","Garanti":"2 yıl"}', 'active', datetime('now'), datetime('now')),

('Bosch Tronic 8500i', 'Elektrikli kombi sistemi. Gaz bağlantısı gerektirmeyen, çevre dostu elektrikli ısıtma çözümü.', 13200, '/uploads/products/bosch-tronic-8500i.png', 'kombi', 'Bosch', 'Tronic 8500i', '["Elektrikli sistem","Gaz gerektirmez","Çevre dostu","Sessiz çalışma","Kompakt tasarım"]', '{"Güç":"24 kW","Elektrik":"380V","Boyutlar":"740x400x299 mm","Ağırlık":"28 kg","Garanti":"2 yıl"}', 'active', datetime('now'), datetime('now')),

('Baymak Lunatec Kombi', 'Ekonomik kondenzli kombi sistemi. Uygun fiyat ve güvenilir performans ile ev tipi ısıtma çözümü.', 8500, '/uploads/products/baymak-lunatec-kombi.png', 'kombi', 'Baymak', 'Lunatec', '["Ekonomik fiyat","Kondenzli sistem","Türk malı","Kolay kurulum","Güvenilir"]', '{"Güç":"24 kW","Verim":"%105","Boyutlar":"730x400x320 mm","Ağırlık":"30 kg","Garanti":"2 yıl"}', 'active', datetime('now'), datetime('now')),

('Buderus Logatherm WLW186i', 'Hava kaynaklı ısı pompası. Çevre dostu soğutucu akışkan ve yüksek verimlilik ile ekonomik ısıtma.', 28900, '/uploads/products/buderus-logatherm-wlw186i.png', 'ısı-pompası', 'Buderus', 'Logatherm WLW186i', '["Hava kaynaklı","Çevre dostu","Yüksek verim","Sessiz işletim","Akıllı kontrol"]', '{"Güç":"14 kW","COP":"4.2","R32 Soğutucu":"Evet","Ses Seviyesi":"55 dB","Garanti":"5 yıl"}', 'active', datetime('now'), datetime('now')),

('Mitsubishi MSZ Split Klima', 'Premium inverter klima sistemi. Gelişmiş filtreleme teknolojisi ve akıllı sensörler ile üstün konfor.', 12800, '/uploads/products/mitsubishi-msz.jpg', 'klima', 'Mitsubishi', 'MSZ', '["Premium kalite","Gelişmiş filtre","Akıllı sensör","Sessiz çalışma","Uzun ömür"]', '{"Soğutma Kapasitesi":"18000 BTU/h","Enerji Sınıfı":"A+++","Ses Seviyesi":"21 dB","Çalışma Sıcaklığı":"-15°C / +46°C","Garanti":"5 yıl"}', 'active', datetime('now'), datetime('now')),

('Purmo Radyatör', 'Panel radyatör sistemi. Yüksek ısı transferi ve estetik tasarım ile modern mekanlar için ideal.', 850, '/uploads/products/purmo-radiator.jpg', 'radyatör', 'Purmo', 'Panel', '["Yüksek ısı transferi","Estetik tasarım","Dayanıklı","Kolay montaj","Çevre dostu"]', '{"Tip":"Tip 22","Boyut":"600x1400 mm","Isı Çıkışı":"2847 W","Malzeme":"Çelik","Garanti":"10 yıl"}', 'active', datetime('now'), datetime('now')); 